# Generated by Django 5.2.8 on 2026-01-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="记录日期")),
                ("weight", models.FloatField(verbose_name="体重 (kg)")),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="身高 (cm)"),
                ),
                (
                    "body_fat_percentage",
                    models.FloatField(blank=True, null=True, verbose_name="体脂率 (%)"),
                ),
                (
                    "muscle_mass",
                    models.FloatField(
                        blank=True, null=True, verbose_name="肌肉量 (kg)"
                    ),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "身体指标记录",
                "verbose_name_plural": "身体指标记录",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "max_weight",
                    models.FloatField(default=0.0, verbose_name="最大重量 (kg)"),
                ),
                (
                    "max_reps",
                    models.IntegerField(default=0, verbose_name="最高单组次数"),
                ),
                (
                    "total_volume",
                    models.FloatField(
                        default=0.0,
                        help_text="重量 * 次数 * 组数",
                        verbose_name="总训练量 (kg)",
                    ),
                ),
                (
                    "best_form_score",
                    models.FloatField(default=0.0, verbose_name="最佳动作评分"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "动作进步追踪",
                "verbose_name_plural": "动作进步追踪",
                "unique_together": {("user", "exercise", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "total_duration_minutes",
                    models.IntegerField(default=0, verbose_name="总训练时长(分)"),
                ),
                (
                    "total_calories_burned",
                    models.FloatField(default=0.0, verbose_name="总消耗卡路里"),
                ),
                (
                    "completed_sessions",
                    models.IntegerField(default=0, verbose_name="完成会话数"),
                ),
                (
                    "completed_exercises",
                    models.IntegerField(default=0, verbose_name="完成动作数"),
                ),
                (
                    "average_form_score",
                    models.FloatField(default=0.0, verbose_name="平均动作评分"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
