# Generated by Django 5.2.8 on 2025-12-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="计划名称")),
                ("description", models.TextField(verbose_name="计划描述")),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "减脂"),
                            ("muscle_gain", "增肌"),
                            ("strength", "力量"),
                            ("endurance", "耐力"),
                            ("flexibility", "柔韧性"),
                            ("general_fitness", "综合健身"),
                        ],
                        max_length=20,
                        verbose_name="训练目标",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "入门"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "duration_weeks",
                    models.IntegerField(
                        default=4,
                        help_text="训练计划总周数",
                        verbose_name="计划周期(周)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "estimated_calories_burned",
                    models.IntegerField(
                        default=0,
                        help_text="整个计划预计消耗的卡路里",
                        verbose_name="预计消耗卡路里",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="每次训练预计时长",
                        verbose_name="预计时长(分钟)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exercises.exercisecategory",
                        verbose_name="训练分类",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练计划",
                "verbose_name_plural": "训练计划",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        help_text="在训练计划中的第几天", verbose_name="第几天"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="例如：上肢力量训练",
                        max_length=100,
                        verbose_name="当日标题",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="当日描述")),
                (
                    "is_rest_day",
                    models.BooleanField(
                        default=False,
                        help_text="如果是休息日，则不包含任何训练动作",
                        verbose_name="是否休息日",
                    ),
                ),
                (
                    "warmup_duration",
                    models.IntegerField(default=5, verbose_name="热身时长(分钟)"),
                ),
                (
                    "cooldown_duration",
                    models.IntegerField(default=5, verbose_name="拉伸时长(分钟)"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingplan",
                        verbose_name="训练计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练计划每日安排",
                "verbose_name_plural": "训练计划每日安排",
                "ordering": ["day_number"],
                "unique_together": {("plan", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="TrainingPlanExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.IntegerField(default=3, verbose_name="组数")),
                ("reps", models.IntegerField(default=10, verbose_name="每组次数")),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=60,
                        help_text="如果是计时动作，则填写每组持续时间",
                        verbose_name="每组时长(秒)",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.0,
                        help_text="如果是重量动作，则填写重量",
                        verbose_name="重量(kg)",
                    ),
                ),
                (
                    "rest_between_sets",
                    models.IntegerField(default=60, verbose_name="组间休息时间(秒)"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="在当天训练中的顺序", verbose_name="顺序"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                        verbose_name="动作",
                    ),
                ),
                (
                    "training_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.trainingplanday",
                        verbose_name="训练计划每日安排",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练计划动作安排",
                "verbose_name_plural": "训练计划动作安排",
                "ordering": ["training_day", "order"],
                "unique_together": {("training_day", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserTrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "total_exercises",
                    models.IntegerField(default=0, verbose_name="总动作数"),
                ),
                (
                    "completed_exercises",
                    models.IntegerField(default=0, verbose_name="已完成动作数"),
                ),
                (
                    "calories_burned",
                    models.FloatField(default=0.0, verbose_name="消耗卡路里"),
                ),
                (
                    "performance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="基于完成度和动作质量的综合评分",
                        verbose_name="表现评分",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="training.trainingplan",
                        verbose_name="训练计划",
                    ),
                ),
                (
                    "plan_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="training.trainingplanday",
                        verbose_name="训练日",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户训练会话",
                "verbose_name_plural": "用户训练会话",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserTrainingExerciseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sets_completed",
                    models.IntegerField(default=0, verbose_name="完成组数"),
                ),
                (
                    "reps_completed",
                    models.JSONField(
                        default=list,
                        help_text="每组实际完成的次数，如[10, 8, 12]",
                        verbose_name="每组完成次数",
                    ),
                ),
                (
                    "weights_used",
                    models.JSONField(
                        default=list,
                        help_text="每组使用的重量，如[20, 20, 20]",
                        verbose_name="每组使用重量",
                    ),
                ),
                (
                    "duration_seconds_actual",
                    models.IntegerField(default=0, verbose_name="实际时长(秒)"),
                ),
                (
                    "form_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI评估的动作质量(0-100)",
                        verbose_name="动作评分",
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        help_text="AI提供的详细动作分析",
                        null=True,
                        verbose_name="动作反馈",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                        verbose_name="动作",
                    ),
                ),
                (
                    "plan_exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="training.trainingplanexercise",
                        verbose_name="计划动作",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_records",
                        to="training.usertrainingsession",
                        verbose_name="训练会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户训练动作记录",
                "verbose_name_plural": "用户训练动作记录",
                "ordering": ["created_at"],
            },
        ),
    ]
