# Generated by Django 5.2.8 on 2026-01-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertrainingsession",
            name="ai_analysis",
            field=models.TextField(
                blank=True,
                help_text="DeepSeek生成的文本分析，包含HTML格式",
                null=True,
                verbose_name="AI分析报告",
            ),
        ),
        migrations.AddField(
            model_name="usertrainingsession",
            name="ai_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI生成的总结性标签，如['核心稳定', '耐力好']",
                null=True,
                verbose_name="AI标签",
            ),
        ),
    ]
