# Generated by Django 5.2.8 on 2026-02-13 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0006_exercise_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("cosine", "余弦相似度 (基于内容)"),
                            ("cf", "协同过滤 (基于用户)"),
                            ("ml_regression", "机器学习回归预测"),
                            ("dl_sequence", "深度学习序列推荐"),
                            ("rl_adaptive", "强化学习动态调整"),
                            ("popularity", "热门推荐 (冷启动)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("rank", models.IntegerField(default=1)),
                (
                    "reason",
                    models.CharField(blank=True, help_text="推荐理由", max_length=255),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "查看"),
                            ("like", "喜欢"),
                            ("skip", "跳过"),
                            ("finish", "完成训练"),
                            ("bookmark", "收藏"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(default=0.0, help_text="归一化后的交互评分"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fatigue_level",
                    models.FloatField(default=0.0, help_text="疲劳度 0-1"),
                ),
                (
                    "consistency_score",
                    models.FloatField(default=0.0, help_text="坚持程度评分"),
                ),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_equipment_available",
                    models.CharField(default="all", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rec_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
