# Generated by Django 5.2.8 on 2026-02-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendedexercise",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("cosine", "余弦相似度 (基于内容)"),
                    ("cf", "协同过滤 (基于用户)"),
                    ("ml_regression", "机器学习回归预测"),
                    ("dl_sequence", "深度学习序列推荐"),
                    ("rl_adaptive", "强化学习动态调整"),
                    ("gnn_reasoning", "图神经网络 (知识图谱分析)"),
                    ("popularity", "热门推荐 (冷启动)"),
                ],
                max_length=20,
            ),
        ),
    ]
