# Generated by Django 5.2.8 on 2026-02-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_alter_recommendedexercise_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstate",
            name="target_intensity",
            field=models.FloatField(default=5.0, help_text="目标强度 1-10"),
        ),
    ]
