# Generated by Django 5.2.8 on 2026-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_userstate_target_intensity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendedexercise",
            name="algorithm",
            field=models.CharField(help_text="使用的推荐算法或场景标识", max_length=50),
        ),
    ]
