# Generated by Django 5.2.8 on 2026-01-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ai_sessions/",
                        verbose_name="原始视频/流路径",
                    ),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="处理帧数"),
                ),
                (
                    "average_confidence",
                    models.FloatField(default=0.0, verbose_name="平均置信度"),
                ),
                (
                    "motion_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="运动轨迹数据"
                    ),
                ),
                (
                    "analysis_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="training.usertrainingexerciserecord",
                        verbose_name="训练记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 分析会话",
                "verbose_name_plural": "AI 分析会话",
            },
        ),
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(max_length=50, verbose_name="模型版本"),
                ),
                (
                    "config_data",
                    models.JSONField(
                        help_text="如角度阈值、关键点索引等", verbose_name="配置参数"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否当前使用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                        verbose_name="关联动作",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 模型配置",
                "verbose_name_plural": "AI 模型配置",
            },
        ),
    ]
