# Generated by Django 5.2.8 on 2026-02-20 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0001_initial"),
        ("exercises", "0006_exercise_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostureDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[("front", "正面"), ("side", "侧面")],
                        default="front",
                        max_length=10,
                        verbose_name="诊断类型",
                    ),
                ),
                ("score", models.IntegerField(default=100, verbose_name="健康评分")),
                (
                    "summary",
                    models.CharField(
                        help_text="例如：轻微圆肩、盆骨前倾",
                        max_length=200,
                        verbose_name="核心结论",
                    ),
                ),
                (
                    "detailed_report",
                    models.JSONField(
                        help_text="存储具体的角度、对称性等数据",
                        verbose_name="详细分析报告",
                    ),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posture_snapshots/",
                        verbose_name="快照",
                    ),
                ),
                (
                    "landmarks_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="关键点原始数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="诊断时间"),
                ),
                (
                    "suggested_exercises",
                    models.ManyToManyField(
                        blank=True,
                        to="exercises.exercise",
                        verbose_name="纠正性训练建议",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "姿态诊断",
                "verbose_name_plural": "姿态诊断",
                "ordering": ["-created_at"],
            },
        ),
    ]
