# Generated by Django 5.2.8 on 2025-11-26 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(default=20, verbose_name="年龄")),
                ("height", models.FloatField(default=170.0, verbose_name="身高 (cm)")),
                ("weight", models.FloatField(default=65.0, verbose_name="体重 (kg)")),
                (
                    "injury_history",
                    models.TextField(
                        blank=True,
                        default="无",
                        help_text="例如：膝盖受损、腰椎间盘突出",
                        verbose_name="伤病史",
                    ),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "新手"),
                            ("intermediate", "进阶"),
                            ("advanced", "大神"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="运动基础",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
