# Generated by Django 5.2.6 on 2025-11-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_name",
                    models.CharField(max_length=50, verbose_name="动作名称"),
                ),
                ("count", models.IntegerField(default=0, verbose_name="完成数量")),
                ("duration", models.IntegerField(default=0, verbose_name="耗时(秒)")),
                (
                    "accuracy_score",
                    models.FloatField(default=0.0, verbose_name="AI评分"),
                ),
                ("calories", models.FloatField(default=0.0, verbose_name="消耗卡路里")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(default=20, verbose_name="年龄")),
                ("height", models.FloatField(default=170.0, verbose_name="身高 (cm)")),
                ("weight", models.FloatField(default=65.0, verbose_name="体重 (kg)")),
                (
                    "injury_history",
                    models.TextField(blank=True, default="无", verbose_name="伤病史"),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "新手"),
                            ("intermediate", "进阶"),
                            ("advanced", "大神"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="运动基础",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
