# Generated by Django 5.2.8 on 2025-12-21 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "久坐不动"),
                    ("light", "轻度活动"),
                    ("moderate", "中度活动"),
                    ("active", "高度活动"),
                    ("very_active", "极高活动"),
                ],
                default="moderate",
                max_length=20,
                verbose_name="日常活动水平",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bmi",
            field=models.FloatField(blank=True, null=True, verbose_name="BMI"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bmr",
            field=models.FloatField(blank=True, null=True, verbose_name="基础代谢率"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_calorie_burn",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="每日消耗热量目标 (卡路里)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_calorie_intake",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="每日摄入热量目标 (卡路里)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="目标达成日期"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="目标体重 (kg)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight_loss", "减重"),
                            ("muscle_gain", "增肌"),
                            ("fitness", "健身"),
                            ("endurance", "耐力提升"),
                        ],
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                ("target_value", models.FloatField(verbose_name="目标值")),
                ("current_value", models.FloatField(default=0, verbose_name="当前值")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("target_date", models.DateField(verbose_name="目标日期")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "achieved",
                    models.BooleanField(default=False, verbose_name="是否达成"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户目标",
                "verbose_name_plural": "用户目标",
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_trainings",
                    models.IntegerField(default=0, verbose_name="总训练次数"),
                ),
                (
                    "total_training_days",
                    models.IntegerField(default=0, verbose_name="总训练天数"),
                ),
                (
                    "total_training_time",
                    models.IntegerField(default=0, verbose_name="总训练时长(分钟)"),
                ),
                (
                    "total_calories_burned",
                    models.FloatField(default=0.0, verbose_name="总消耗卡路里"),
                ),
                (
                    "best_accuracy_score",
                    models.FloatField(default=0.0, verbose_name="最佳动作准确度"),
                ),
                (
                    "longest_training_streak",
                    models.IntegerField(default=0, verbose_name="最长连续训练天数"),
                ),
                (
                    "weekly_trainings",
                    models.IntegerField(default=0, verbose_name="本周训练次数"),
                ),
                (
                    "monthly_trainings",
                    models.IntegerField(default=0, verbose_name="本月训练次数"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户统计数据",
                "verbose_name_plural": "用户统计数据",
            },
        ),
    ]
