# Generated by Django 5.2.8 on 2025-11-26 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="injury_history",
            field=models.TextField(blank=True, default="无", verbose_name="伤病史"),
        ),
        migrations.CreateModel(
            name="TrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_name",
                    models.CharField(max_length=50, verbose_name="动作名称"),
                ),
                ("count", models.IntegerField(default=0, verbose_name="完成数量")),
                ("duration", models.IntegerField(default=0, verbose_name="耗时(秒)")),
                (
                    "accuracy_score",
                    models.FloatField(default=0.0, verbose_name="AI评分"),
                ),
                ("calories", models.FloatField(default=0.0, verbose_name="消耗卡路里")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
