# Generated by Django 5.2.8 on 2025-12-20 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="分类图标标识",
                        max_length=100,
                        verbose_name="图标",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="显示顺序，数值越小越靠前",
                        verbose_name="排序",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "动作分类",
                "verbose_name_plural": "动作分类",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="动作名称"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="英文名称"
                    ),
                ),
                ("description", models.TextField(verbose_name="动作描述")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "入门"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("none", "无器械"),
                            ("dumbbell", "哑铃"),
                            ("barbell", "杠铃"),
                            ("resistance_band", "阻力带"),
                            ("kettlebell", "壶铃"),
                            ("machine", "器械"),
                            ("other", "其他"),
                        ],
                        default="none",
                        max_length=30,
                        verbose_name="所需器材",
                    ),
                ),
                (
                    "target_muscle",
                    models.CharField(
                        choices=[
                            ("chest", "胸部"),
                            ("back", "背部"),
                            ("shoulders", "肩部"),
                            ("arms", "手臂"),
                            ("abs", "腹部"),
                            ("legs", "腿部"),
                            ("glutes", "臀部"),
                            ("full_body", "全身"),
                        ],
                        max_length=20,
                        verbose_name="目标肌群",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="详细的执行步骤", verbose_name="动作要领"
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True,
                        help_text="安全提示和常见错误",
                        verbose_name="注意事项",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="教学视频链接")),
                ("image_url", models.URLField(blank=True, verbose_name="动作图片链接")),
                (
                    "keypoints",
                    models.JSONField(
                        blank=True,
                        help_text="动作标准姿态的关键点坐标数据",
                        null=True,
                        verbose_name="关键点坐标",
                    ),
                ),
                (
                    "angle_thresholds",
                    models.JSONField(
                        blank=True,
                        help_text="各关节角度评判标准，如{'knee_min': 90}",
                        null=True,
                        verbose_name="角度阈值",
                    ),
                ),
                (
                    "correction_tips",
                    models.JSONField(
                        blank=True,
                        help_text="常见错误及纠正方法，如{'knee_cave': '膝盖不要内扣'}",
                        null=True,
                        verbose_name="纠正提示",
                    ),
                ),
                (
                    "default_duration",
                    models.IntegerField(
                        default=60,
                        help_text="建议的单次训练时长",
                        verbose_name="默认时长(秒)",
                    ),
                ),
                (
                    "default_reps",
                    models.IntegerField(
                        default=10,
                        help_text="建议的单次训练次数",
                        verbose_name="默认次数",
                    ),
                ),
                (
                    "calories_burned",
                    models.FloatField(
                        default=5.0,
                        help_text="每分钟平均消耗的卡路里",
                        verbose_name="每分钟消耗(卡路里)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="显示顺序", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exercises.exercisecategory",
                        verbose_name="动作分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "健身动作",
                "verbose_name_plural": "健身动作",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserExerciseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="完成次数")),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="训练时长(秒)"),
                ),
                (
                    "accuracy_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI评估的动作准确性(0-100)",
                        verbose_name="准确度评分",
                    ),
                ),
                (
                    "calories_burned",
                    models.FloatField(default=0.0, verbose_name="消耗卡路里"),
                ),
                (
                    "form_feedback",
                    models.JSONField(
                        blank=True,
                        help_text="AI提供的详细动作分析",
                        null=True,
                        verbose_name="动作反馈",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                        verbose_name="动作",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户动作记录",
                "verbose_name_plural": "用户动作记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
