# Generated by Django 5.2.8 on 2026-01-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisecategory",
            name="demo_gif",
            field=models.FileField(
                blank=True,
                help_text="上传标准动作的 GIF 动图或短视频",
                null=True,
                upload_to="exercises/demos/",
                verbose_name="动作演示",
            ),
        ),
    ]
