# Generated by Django 5.2.8 on 2026-02-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_remove_exercisecategory_demo_gif_exercise_demo_gif"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisecategory",
            name="level",
            field=models.IntegerField(default=1, verbose_name="难度等级"),
        ),
        migrations.AddField(
            model_name="exercisecategory",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks",
                to="exercises.exercisecategory",
                verbose_name="前置解锁动作",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(default=0)),
                ("probability", models.FloatField(default=0.0)),
                (
                    "from_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_paths",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "to_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prev_paths",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["-probability"],
                "unique_together": {("from_exercise", "to_exercise")},
            },
        ),
    ]
