# Generated by Django 5.2.8 on 2026-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_exercisecategory_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercisecategory",
            name="level",
        ),
        migrations.RemoveField(
            model_name="exercisecategory",
            name="prerequisites",
        ),
        migrations.AddField(
            model_name="exercise",
            name="level",
            field=models.IntegerField(
                default=1, help_text="1:入门, 5:大神", verbose_name="难度等级(逻辑用)"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks",
                to="exercises.exercise",
                verbose_name="前置解锁动作",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "入门"),
                    ("intermediate", "中级"),
                    ("advanced", "高级"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="难度等级(显示用)",
            ),
        ),
    ]
