# Generated by Django 5.2.8 on 2026-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_remove_exercisecategory_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="动作的关键词标签，建议不超过5个",
                verbose_name="动作标签",
            ),
        ),
    ]
